### ISSUE TITLE
KeyError: 'reUrl'

### ISSUE THREAD

**Issue by NovaTech-H** [sdk250/Auto-Test#1]
Version: 1.1.2
2024-05-15 20:53
Traceback (most recent call last):
  File "/ql/data/scripts/autoyiban/run.py", line 28, in <module>
    cookies = Cookies(
              ^^^^^^^^
  File "/ql/data/scripts/autoyiban/cookies.py", line 23, in __init__
    self.cookies = self._cookies(account = self.account, password = self.password)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/ql/data/scripts/autoyiban/cookies.py", line 84, in _cookies
    if "error" in loads(result.text)["reUrl"]:
                  ~~~~~~~~~~~~~~~~~~^^^^^^^^^
KeyError: 'reUrl'

**Comment by sdk250** [comment]
[1.1.4](https://github.com/sdk250/Auto-Test/tree/main) 已经修复了这个问题，原因是易班又新加了一个验证
